# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

safe: false
source: .
destination: ../build
plugins: ./_plugins
lsi: false
pygments: true

auto: true # automatically update your jekyll
server: true # runs a local server
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", "source", ".gitignore"] # files to exclude

assets:
  dirname: assets
  sources:
    - _assets/img
    - _assets/js
    - _assets/css
  compress:
    js:  uglifier
    css: sass
  cachebust: hard
  gzip: [ text/css, application/javascript ]
